name: dupont
channels:
  - defaults
  - conda-forge  
  # to install snakemake
  - bioconda
  - alubbock 

# installed with conda
dependencies:
  - python==3.7
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - flask
  - dask
  - bokeh
  - requests
  - pip
  - mdanalysis
  - scipy
  - biopython
  - nglview
  - pip:
    # works for regular pip packages
    - python-dotenv>=0.5.1
    - click
    - jupyter-contrib-nbextension
    - scipy
    - biopython
    - jinja2
    - requests
    - plotnine
    - tensorflow
    - keras